### ISSUE TITLE
'CountryDropdown' cannot be used as a JSX component.   Its instance type 'CountryDropdown' is not a valid JSX element.

### ISSUE THREAD

**Issue by AryanJ-NYC** [country-regions/react-country-region-selector#161]
In a new next.js project, using `CountryDropdown` emits the following TypeScript error:

```
'CountryDropdown' cannot be used as a JSX component.
  Its instance type 'CountryDropdown' is not a valid JSX element.
```

https://stackblitz.com/edit/stackblitz-starters-nu8823?file=app%2Fpage.tsx

**Comment by benkeen** [comment]
Thanks @AryanJ-NYC. I'm just in the process of modernizing the code now. I'll convert it to TS, modern React and provide appropriate typings.

**Comment by benkeen** [comment]
_Annnnnd_.... updated. `4.0.0` was just released with updated typings. I hit this same problem locally btw and it turns out there was a mismatch of the @types/react package in my consuming repo: I had a react version specific that didn't match with the types. 

New doc: 
https://country-regions.github.io/react-country-region-selector/

Re-open if you still have problems.
