### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by SimonSchick** [country-regions/react-country-region-selector#52]
As you know we've been using this library and it's working pretty well, we created some typings for internal use and would like you to publish them with your packages so others can use them too:

Contra:
 - Are you down to ship and maintain them?
 - ~They are not exactly complete~ You might want to check this
 - You re-export `country-region-data` which has no typings, I had to include them.
   - You might want to consider removing this export actually, if people want access to that list, tell them to import it from the package instead.
 - You broke the `onChange` interface contract (probably not intentionally), by calling `onChange` with the value of the input as first arg, which prevents me from extending `InputHTMLAttributes`.

Pro:
 - You would make development with your library about 5x easier for anyone using TS.
 - You get additional documentation for free

```ts
declare module 'react-country-region-selector' {
  import { InputHTMLAttributes } from 'react';

  interface Region {
    name: string;
    shortCode: string;
  }

  interface Country {
    countryName: string;
    countryShortCode: string;
    regions: Region[];
  }

  interface ReactCountryDropdownProps extends InputHTMLAttributes<string> {
    value: string;
    classes?: string;
    showDefaultOption?: boolean;
    defaultOptionLabel?: string | number;
    labelType?: number;
    valueType?: 'short' | 'full';
    whitelist?: string[];
    blacklist?: string[];
  }

  interface ReactRegionDropdownProps extends InputHTMLAttributes<string> {
    country: string;
    value: string | number;
    classes?: string;
    showDefaultOption?: boolean;
    defaultOptionLabel?: string | number;
    labelType?: number;
    countryValueType?: 'short' | 'full';
    whitelist?: string[];
    blacklist?: string[];
    disableWhenEmpty?: boolean;
  }

  class CountryDropdown extends React.Component<ReactCountryDropdownProps> {}
  class RegionDropdown extends React.Component<ReactRegionDropdownProps> {}

  const CountryRegionData: Country[];

  export { CountryDropdown, RegionDropdown, CountryRegionData };
}
```

**Comment by benkeen** [comment]
Hey @SimonSchick,

Thanks! Actually I wouldn't mind converting this whole lib to Typescript; a standalone library like this would benefit from it. But I'm going to have to turn back to another project for a couple of weeks before returning to this project. I can look at the Typescript change then.

> Are you down to ship and maintain them?
Yup.

> You re-export country-region-data which has no typings, I had to include them. You might want to consider removing this export actually, if people want access to that list, tell them to import it from the package instead.
Actually they're a bit different. The country-region-data info exported via the library is in a slightly different format (serialized to reduce the size of the lib) and the list may differ depending on whether the RCRS library was built on the command line to limit the list of countries that appear. I think exporting the info along with the two components make sense - very easy to consume as a developer should you need it.

> You broke the onChange interface contract (probably not intentionally), by calling onChange with the value of the input as first arg, which prevents me from extending InputHTMLAttributes
I actually don't quite follow this one... I checked the history back to 1.0.0 and it's always had an `onChange` callback whose first param is the selected value; I added in the second parameter (the full event) later on because I figured it was useful. My Typescript is pretty rusty but presumably that can be configured somehow.

Regarding the "pros", I absolutely agree.

**Comment by SimonSchick** [comment]
@benkeen default `input` `onChange` signature doesn't provide the value, only the reference to element, that's what I mean.

**Comment by benkeen** [comment]
Ah, gotcha! Thanks.

**Comment by creepygiraff** [comment]
I´m trying to implement this with typescript (wich is pretty new to me) in a sharpoint webpart (propertypane). The question is: could you give an example on how you implement it in ts?

**Comment by benkeen** [comment]
Hey folks. `4.0.0` was just released which was a complete rewrite in TS, including new typings. Ping me with any issues yoyu encounter!
